- name: Download flink
  get_url: url='{{flink_url}}' dest='/tmp/{{flink_archive}}'

- name: Unarchive flink
  become_user: "{{user_name}}"
  unarchive: copy=no src='/tmp/{{flink_archive}}' dest='~/'

- name: Link flink
  become_user: "{{user_name}}"
  file: src='~/{{flink_name}}' dest='~/flink' state=link

- name: Add flink to path
  become_user: "{{user_name}}"
  shell: echo "export PATH=$PATH:~/flink/bin" >> .bash_profile

- name: Copy flink config
  become_user: "{{user_name}}"
  copy: src=flink-conf.yaml dest=~/flink/conf

- name: Copy examples
  become_user: "{{user_name}}"
  copy: src=examples dest=~/

- name: Copy tests
  become_user: "{{user_name}}"
  copy: src=tests dest=~/
